import { Card } from '@/components/ui/card';
import {
    MonthComparisonCell,
    monthOverMonthPercentChange,
} from '@/components/reports/month-comparison-cell';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import { formatCurrency } from '@/lib/utils';
import { useMemo } from 'react';

/**
 * @param {number} payments
 * @param {number} expected
 */
function collectionRatePercent(payments, expected) {
    if (!expected || expected <= 0) {
        return 0;
    }

    return Math.min(100, Math.round((payments / expected) * 1000) / 10);
}

/**
 * @param {number} payments
 * @param {number} expected
 */
function formatCollectionRate(payments, expected) {
    return `${collectionRatePercent(payments, expected).toLocaleString(undefined, {
        maximumFractionDigits: 1,
        minimumFractionDigits: 0,
    })}%`;
}

/**
 * @param {Array<{
 *   month: string,
 *   label: string,
 *   amount_expected: number,
 *   payments_amount: number,
 * }>} rows
 */
function monthlyRowsWithComparison(rows) {
    return rows.map((row, index) => {
        const previous = index > 0 ? rows[index - 1] : null;

        return {
            ...row,
            previousMonthLabel: previous?.label ?? null,
            paymentsChangePct: previous
                ? monthOverMonthPercentChange(row.payments_amount, previous.payments_amount)
                : null,
        };
    });
}

/**
 * @param {{
 *   monthlyBreakdown?: Array<{
 *     month: string,
 *     label: string,
 *     amount_expected: number,
 *     payments_amount: number,
 *   }>,
 *   year?: number,
 *   totals?: { amount_expected?: number, payments_amount?: number },
 * }} props
 */
export function RevenueMonthlyBreakdownTable({ monthlyBreakdown = [], year, totals }) {
    const displayYear = year ?? new Date().getFullYear();
    const monthlyRows = useMemo(() => monthlyRowsWithComparison(monthlyBreakdown), [monthlyBreakdown]);

    const footerTotals = useMemo(() => {
        if (totals) {
            return {
                amount_expected: totals.amount_expected ?? 0,
                payments_amount: totals.payments_amount ?? 0,
            };
        }

        return monthlyBreakdown.reduce(
            (acc, row) => ({
                amount_expected: acc.amount_expected + Number(row.amount_expected ?? 0),
                payments_amount: acc.payments_amount + Number(row.payments_amount ?? 0),
            }),
            { amount_expected: 0, payments_amount: 0 },
        );
    }, [monthlyBreakdown, totals]);

    const footerCollectionRate = collectionRatePercent(
        footerTotals.payments_amount,
        footerTotals.amount_expected,
    );

    const currentMonthKey = `${displayYear}-${String(new Date().getMonth() + 1).padStart(2, '0')}`;

    return (
        <Card className="overflow-hidden border border-border/60 bg-card shadow-sm">
            <div className="border-b bg-card px-5 py-4">
                <h2 className="text-sm font-semibold text-foreground">Month-by-month breakdown</h2>
                <p className="mt-1 text-xs text-muted-foreground">
                    Bills generated by issue date; collections by payment date ({displayYear}).
                </p>
            </div>
            <Table>
                <TableHeader>
                    <TableRow className="bg-muted/30 hover:bg-muted/30">
                        <TableHead className="pl-5 font-semibold text-foreground">Month</TableHead>
                        <TableHead className="text-right font-semibold text-foreground">
                            Bills generated (SSP)
                        </TableHead>
                        <TableHead className="text-right font-semibold text-foreground">Collected (SSP)</TableHead>
                        <TableHead className="text-right font-semibold text-foreground">Collection rate</TableHead>
                        <TableHead className="pr-5 text-right font-semibold text-foreground">vs prior month</TableHead>
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {monthlyRows.map((row) => (
                        <TableRow
                            key={row.month}
                            className={row.month === currentMonthKey ? 'bg-sky-50/60 dark:bg-sky-950/20' : undefined}
                        >
                            <TableCell className="pl-5 font-medium">{row.label.split(' ')[0]}</TableCell>
                            <TableCell className="text-right font-mono text-sm tabular-nums">
                                {formatCurrency(row.amount_expected)}
                            </TableCell>
                            <TableCell className="text-right font-mono text-sm tabular-nums">
                                {formatCurrency(row.payments_amount)}
                            </TableCell>
                            <TableCell className="text-right font-mono text-sm tabular-nums">
                                {formatCollectionRate(row.payments_amount, row.amount_expected)}
                            </TableCell>
                            <TableCell className="pr-5">
                                <MonthComparisonCell
                                    paymentsChangePct={row.paymentsChangePct}
                                    previousMonthLabel={row.previousMonthLabel}
                                />
                            </TableCell>
                        </TableRow>
                    ))}
                    {monthlyRows.length === 0 && (
                        <TableRow>
                            <TableCell
                                colSpan={5}
                                className="py-12 text-center text-sm text-muted-foreground"
                            >
                                No months in this period.
                            </TableCell>
                        </TableRow>
                    )}
                </TableBody>
                {monthlyRows.length > 0 && (
                    <tfoot>
                        <TableRow className="border-t bg-sky-50/80 font-semibold hover:bg-sky-50/80 dark:bg-sky-950/30">
                            <TableCell className="pl-5">Full year</TableCell>
                            <TableCell className="text-right font-mono tabular-nums">
                                {formatCurrency(footerTotals.amount_expected)}
                            </TableCell>
                            <TableCell className="text-right font-mono tabular-nums">
                                {formatCurrency(footerTotals.payments_amount)}
                            </TableCell>
                            <TableCell className="text-right">
                                <span className="inline-flex rounded-md bg-red-100 px-2 py-0.5 font-mono text-sm tabular-nums text-red-800 dark:bg-red-950/50 dark:text-red-200">
                                    {footerCollectionRate.toLocaleString(undefined, {
                                        maximumFractionDigits: 1,
                                        minimumFractionDigits: 0,
                                    })}
                                    %
                                </span>
                            </TableCell>
                            <TableCell className="pr-5" />
                        </TableRow>
                    </tfoot>
                )}
            </Table>
        </Card>
    );
}
