<?php

namespace App\Notifications;

use App\Models\Bill;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class BillGeneratedNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public $bill;

    /**
     * Create a new notification instance.
     */
    public function __construct(Bill $bill)
    {
        $this->bill = $bill;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    /**
     * Get the mail representation of the notification.
     */
    public function toMail(object $notifiable): MailMessage
    {
        $customer = $this->bill->customer;
        $generatedBy = $this->bill->generatedBy;
        
        return (new MailMessage)
            ->subject('New Bill Generated - AquaBill System')
            ->greeting('Hello Admin!')
            ->line('A new bill has been generated in the AquaBill system.')
            ->line("**Bill Details:**")
            ->line("• Customer: {$customer->name} ({$customer->account_number})")
            ->line("• Bill Amount: ₦" . number_format($this->bill->total_amount, 2))
            ->line("• Consumption: {$this->bill->consumption} units")
            ->line("• Billing Period: {$this->bill->billing_period_start->format('M d, Y')} - {$this->bill->billing_period_end->format('M d, Y')}")
            ->line("• Generated by: {$generatedBy->name}")
            ->line("• Generated at: {$this->bill->created_at->format('M d, Y H:i:s')}")
            ->action('View Bill Details', route('bills.show', $this->bill->id))
            ->line('Please review the bill details in the system.')
            ->salutation('Best regards, AquaBill System');
    }

    /**
     * Get the array representation of the notification.
     *
     * @return array<string, mixed>
     */
    public function toArray(object $notifiable): array
    {
        $customer = $this->bill->customer;
        $generatedBy = $this->bill->generatedBy;
        
        return [
            'type' => 'bill_generated',
            'bill_id' => $this->bill->id,
            'customer_name' => $customer->name,
            'customer_account' => $customer->account_number,
            'amount' => $this->bill->total_amount,
            'consumption' => $this->bill->consumption,
            'generated_by' => $generatedBy->name,
            'generated_at' => $this->bill->created_at,
            'billing_period' => $this->bill->billing_period_start->format('M d') . ' - ' . $this->bill->billing_period_end->format('M d, Y'),
        ];
    }
}
