<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'status',
        'department_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    /**
     * Get the department this user belongs to.
     */
    public function department()
    {
        return $this->belongsTo(Department::class);
    }

    /**
     * Get the roles assigned to this user.
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class, 'user_roles')
                    ->withPivot('department_id')
                    ->withTimestamps();
    }

    /**
     * Get the user role assignments.
     */
    public function userRoles()
    {
        return $this->hasMany(UserRole::class);
    }

    /**
     * Get the meter readings recorded by this user.
     */
    public function meterReadings()
    {
        return $this->hasMany(MeterReading::class, 'billing_officer');
    }

    /**
     * Get the bills generated by this user.
     */
    public function generatedBills()
    {
        return $this->hasMany(Bill::class, 'generated_by');
    }

    /**
     * Get the payments received by this user.
     */
    public function receivedPayments()
    {
        return $this->hasMany(Payment::class, 'received_by');
    }

    /**
     * Get the inventory transactions handled by this user.
     */
    public function inventoryTransactions()
    {
        return $this->hasMany(InventoryTransaction::class, 'handled_by');
    }

    /**
     * Get the maintenance requests handled by this user.
     */
    public function maintenanceRequests()
    {
        return $this->hasMany(MaintenanceRequest::class, 'handled_by');
    }

    /**
     * Get the vehicles assigned to this user.
     */
    public function assignedVehicles()
    {
        return $this->hasMany(Vehicle::class, 'assigned_to');
    }

    /**
     * Check if user has a specific role
     */
    public function hasRole($roleName)
    {
        return $this->roles()->where('name', $roleName)->exists();
    }

    /**
     * Check if user is admin
     */
    public function isAdmin()
    {
        return $this->hasRole('admin');
    }

    /**
     * Check if user is manager
     */
    public function isManager()
    {
        return $this->hasRole('manager');
    }

    /**
     * Check if user is regular user
     */
    public function isUser()
    {
        return $this->hasRole('user');
    }

    /**
     * Assign a role to the user
     */
    public function assignRole($roleName, $departmentId = null)
    {
        $role = Role::where('name', $roleName)->first();
        if ($role) {
            $this->roles()->attach($role->id, ['department_id' => $departmentId]);
        }
    }

    /**
     * Remove a role from the user
     */
    public function removeRole($roleName)
    {
        $role = Role::where('name', $roleName)->first();
        if ($role) {
            $this->roles()->detach($role->id);
        }
    }
}
